scss_files: "app/stylesheets/**/*.scss"

exclude: 'app/stylesheets/third-party/*.scss'

linters:
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  HexNotation:
    enabled: false

  SelectorFormat:
    convention: 'hyphenated_BEM'
